spring:
  application:
    name: school
  datasource:
    url: jdbc:mysql://119.45.222.230:3306/bolang?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: bolang
    password: bolang@123
    driver-class-name: com.mysql.cj.jdbc.Driver
