server:
  port: 80

spring:
  application:
    name: bolang-test
  datasource:
    url: jdbc:mysql://119.45.222.230:3306/nft?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: test12
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: false
    database: MYSQL
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    show-sql: true
    generate-ddl: false
    open-in-view: true
  data:
    jpa:
      repositories:
        enabled: true
  session:
    timeout: 7200
